// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pole/chain/pole/v1/genesis.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GenesisState struct {
	Params            *Params               `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	BatchCommits      []*BatchCommit        `protobuf:"bytes,2,rep,name=batch_commits,json=batchCommits,proto3" json:"batch_commits,omitempty"`
	EpochCommits      []*EpochCommit        `protobuf:"bytes,3,rep,name=epoch_commits,json=epochCommits,proto3" json:"epoch_commits,omitempty"`
	RewardRecords     []*RewardRecord       `protobuf:"bytes,4,rep,name=reward_records,json=rewardRecords,proto3" json:"reward_records,omitempty"`
	AggregateRecords  []*AggregateRecord    `protobuf:"bytes,5,rep,name=aggregate_records,json=aggregateRecords,proto3" json:"aggregate_records,omitempty"`
	Challenges        []*Challenge          `protobuf:"bytes,6,rep,name=challenges,proto3" json:"challenges,omitempty"`
	Availability      []*AvailabilityRecord `protobuf:"bytes,7,rep,name=availability,proto3" json:"availability,omitempty"`
	GameWeightEntries []*GameWeightEntry    `protobuf:"bytes,8,rep,name=game_weight_entries,json=gameWeightEntries,proto3" json:"game_weight_entries,omitempty"`
	ClaimedRewards    []*ClaimedReward      `protobuf:"bytes,9,rep,name=claimed_rewards,json=claimedRewards,proto3" json:"claimed_rewards,omitempty"`
	ReplicaReceipts   []*ReplicaReceipt     `protobuf:"bytes,10,rep,name=replica_receipts,json=replicaReceipts,proto3" json:"replica_receipts,omitempty"`
	Nodes             []*NodeRecord         `protobuf:"bytes,11,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_eaf31bebd690ef46, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() *Params {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *GenesisState) GetBatchCommits() []*BatchCommit {
	if m != nil {
		return m.BatchCommits
	}
	return nil
}

func (m *GenesisState) GetEpochCommits() []*EpochCommit {
	if m != nil {
		return m.EpochCommits
	}
	return nil
}

func (m *GenesisState) GetRewardRecords() []*RewardRecord {
	if m != nil {
		return m.RewardRecords
	}
	return nil
}

func (m *GenesisState) GetAggregateRecords() []*AggregateRecord {
	if m != nil {
		return m.AggregateRecords
	}
	return nil
}

func (m *GenesisState) GetChallenges() []*Challenge {
	if m != nil {
		return m.Challenges
	}
	return nil
}

func (m *GenesisState) GetAvailability() []*AvailabilityRecord {
	if m != nil {
		return m.Availability
	}
	return nil
}

func (m *GenesisState) GetGameWeightEntries() []*GameWeightEntry {
	if m != nil {
		return m.GameWeightEntries
	}
	return nil
}

func (m *GenesisState) GetClaimedRewards() []*ClaimedReward {
	if m != nil {
		return m.ClaimedRewards
	}
	return nil
}

func (m *GenesisState) GetReplicaReceipts() []*ReplicaReceipt {
	if m != nil {
		return m.ReplicaReceipts
	}
	return nil
}

func (m *GenesisState) GetNodes() []*NodeRecord {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "pole.chain.pole.v1.GenesisState")
}

func init() { proto.RegisterFile("pole/chain/pole/v1/genesis.proto", fileDescriptor_eaf31bebd690ef46) }

var fileDescriptor_eaf31bebd690ef46 = []byte{
	// 448 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0xb3, 0xd6, 0x46, 0x9d, 0xa4, 0xbf, 0xc6, 0xcb, 0x50, 0x70, 0x8d, 0x15, 0x4a, 0x4f,
	0x1b, 0x1a, 0xbd, 0x7a, 0xb0, 0xb5, 0x04, 0x04, 0xa5, 0x4c, 0x0f, 0x82, 0x97, 0xf0, 0xb2, 0x79,
	0x6c, 0x06, 0xf6, 0x17, 0xf3, 0x86, 0xd4, 0xfc, 0x17, 0x9e, 0xfd, 0x8b, 0x3c, 0xf6, 0xe8, 0x51,
	0x92, 0x7f, 0x44, 0xf6, 0x6d, 0x62, 0x77, 0xe9, 0xf4, 0x36, 0xef, 0xf1, 0xf9, 0x7e, 0x98, 0x79,
	0x8f, 0x11, 0x83, 0xb2, 0x48, 0x71, 0x18, 0xcf, 0xc1, 0xe4, 0x43, 0x3e, 0x2e, 0xce, 0x87, 0x09,
	0xe6, 0x48, 0x86, 0xa2, 0xd2, 0x16, 0xae, 0x90, 0xb2, 0x6a, 0x47, 0x4c, 0x44, 0x7c, 0x5c, 0x9c,
	0x1f, 0x87, 0x9e, 0x14, 0x39, 0x70, 0x58, 0x67, 0x4e, 0x7e, 0x75, 0x45, 0x7f, 0x5c, 0x5b, 0x6e,
	0xaa, 0xb6, 0x1c, 0x89, 0x6e, 0x09, 0x16, 0x32, 0x52, 0xc1, 0x20, 0x38, 0xeb, 0x8d, 0x8e, 0xa3,
	0x87, 0xd6, 0xe8, 0x9a, 0x09, 0xbd, 0x21, 0xe5, 0x27, 0xb1, 0x37, 0x05, 0x17, 0xcf, 0x27, 0x71,
	0x91, 0x65, 0xc6, 0x91, 0x7a, 0x32, 0xd8, 0x39, 0xeb, 0x8d, 0x5e, 0xfb, 0xa2, 0x17, 0x15, 0x78,
	0xc9, 0x9c, 0xee, 0x4f, 0xef, 0x0b, 0xb6, 0x60, 0x59, 0x34, 0x2c, 0x3b, 0x8f, 0x5b, 0xae, 0x2a,
	0x70, 0x6b, 0xc1, 0xfb, 0x82, 0xe4, 0x58, 0xec, 0x5b, 0xbc, 0x05, 0x3b, 0x9b, 0x58, 0x8c, 0x0b,
	0x3b, 0x23, 0xf5, 0x94, 0x35, 0x03, 0x9f, 0x46, 0x33, 0xa9, 0x19, 0xd4, 0x7b, 0xb6, 0x51, 0x91,
	0xbc, 0x16, 0x47, 0x90, 0x24, 0x16, 0x13, 0x70, 0xf8, 0xdf, 0xb5, 0xcb, 0xae, 0xb7, 0x3e, 0xd7,
	0xc7, 0x2d, 0xbc, 0xd1, 0x1d, 0x42, 0xbb, 0x41, 0xf2, 0x83, 0x10, 0xf1, 0x1c, 0xd2, 0x14, 0xf3,
	0x04, 0x49, 0x75, 0x59, 0xf5, 0xca, 0xa7, 0xba, 0xdc, 0x52, 0xba, 0x11, 0x90, 0x9f, 0x45, 0x1f,
	0x16, 0x60, 0x52, 0x98, 0x9a, 0xd4, 0xb8, 0xa5, 0x7a, 0xc6, 0x82, 0x53, 0xef, 0x5d, 0x1a, 0xdc,
	0xe6, 0x3a, 0xad, 0xac, 0xbc, 0x11, 0x2f, 0x13, 0xc8, 0x70, 0x72, 0x8b, 0x26, 0x99, 0xbb, 0x09,
	0xe6, 0xce, 0x1a, 0x24, 0xf5, 0xfc, 0xf1, 0xe7, 0x8d, 0x21, 0xc3, 0x6f, 0x4c, 0x5f, 0xe5, 0xce,
	0x2e, 0xf5, 0x51, 0xd2, 0x6a, 0x18, 0xbe, 0xe0, 0x41, 0x9c, 0x82, 0xc9, 0xb0, 0x9a, 0x7d, 0x35,
	0x4a, 0x52, 0x2f, 0x58, 0xf8, 0xc6, 0xfb, 0xc8, 0x1a, 0xdd, 0xac, 0x60, 0x3f, 0x6e, 0x96, 0x24,
	0xbf, 0x88, 0x43, 0x8b, 0x65, 0x6a, 0x62, 0xa8, 0x66, 0x8f, 0xa6, 0x74, 0xa4, 0x04, 0xcb, 0x4e,
	0xfc, 0x8b, 0x64, 0x56, 0xd7, 0xa8, 0x3e, 0xb0, 0xad, 0x9a, 0xe4, 0x7b, 0xb1, 0x9b, 0x17, 0x33,
	0x24, 0xd5, 0x63, 0x47, 0xe8, 0x73, 0x7c, 0x2d, 0x66, 0xdb, 0xdd, 0xd5, 0xf0, 0xc5, 0xe9, 0xef,
	0x55, 0x18, 0xdc, 0xad, 0xc2, 0xe0, 0xef, 0x2a, 0x0c, 0x7e, 0xae, 0xc3, 0xce, 0xdd, 0x3a, 0xec,
	0xfc, 0x59, 0x87, 0x9d, 0xef, 0xfd, 0x1f, 0xf5, 0x6f, 0x72, 0xcb, 0x12, 0x69, 0xda, 0xe5, 0xbf,
	0xf4, 0xee, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0xed, 0x22, 0x15, 0xa3, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for iNdEx := len(m.Nodes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Nodes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.ReplicaReceipts) > 0 {
		for iNdEx := len(m.ReplicaReceipts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReplicaReceipts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.ClaimedRewards) > 0 {
		for iNdEx := len(m.ClaimedRewards) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ClaimedRewards[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.GameWeightEntries) > 0 {
		for iNdEx := len(m.GameWeightEntries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GameWeightEntries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.Availability) > 0 {
		for iNdEx := len(m.Availability) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Availability[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Challenges) > 0 {
		for iNdEx := len(m.Challenges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Challenges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.AggregateRecords) > 0 {
		for iNdEx := len(m.AggregateRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AggregateRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.RewardRecords) > 0 {
		for iNdEx := len(m.RewardRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RewardRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.EpochCommits) > 0 {
		for iNdEx := len(m.EpochCommits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EpochCommits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.BatchCommits) > 0 {
		for iNdEx := len(m.BatchCommits) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BatchCommits[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.BatchCommits) > 0 {
		for _, e := range m.BatchCommits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.EpochCommits) > 0 {
		for _, e := range m.EpochCommits {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.RewardRecords) > 0 {
		for _, e := range m.RewardRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.AggregateRecords) > 0 {
		for _, e := range m.AggregateRecords {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Challenges) > 0 {
		for _, e := range m.Challenges {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Availability) > 0 {
		for _, e := range m.Availability {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GameWeightEntries) > 0 {
		for _, e := range m.GameWeightEntries {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ClaimedRewards) > 0 {
		for _, e := range m.ClaimedRewards {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ReplicaReceipts) > 0 {
		for _, e := range m.ReplicaReceipts {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &Params{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchCommits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BatchCommits = append(m.BatchCommits, &BatchCommit{})
			if err := m.BatchCommits[len(m.BatchCommits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochCommits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EpochCommits = append(m.EpochCommits, &EpochCommit{})
			if err := m.EpochCommits[len(m.EpochCommits)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RewardRecords = append(m.RewardRecords, &RewardRecord{})
			if err := m.RewardRecords[len(m.RewardRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AggregateRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AggregateRecords = append(m.AggregateRecords, &AggregateRecord{})
			if err := m.AggregateRecords[len(m.AggregateRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Challenges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Challenges = append(m.Challenges, &Challenge{})
			if err := m.Challenges[len(m.Challenges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Availability", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Availability = append(m.Availability, &AvailabilityRecord{})
			if err := m.Availability[len(m.Availability)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GameWeightEntries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GameWeightEntries = append(m.GameWeightEntries, &GameWeightEntry{})
			if err := m.GameWeightEntries[len(m.GameWeightEntries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClaimedRewards", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClaimedRewards = append(m.ClaimedRewards, &ClaimedReward{})
			if err := m.ClaimedRewards[len(m.ClaimedRewards)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReplicaReceipts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReplicaReceipts = append(m.ReplicaReceipts, &ReplicaReceipt{})
			if err := m.ReplicaReceipts[len(m.ReplicaReceipts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &NodeRecord{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
